### ISSUE TITLE
CentOS

### ISSUE THREAD

**Issue by MainFighter** [blackawps/gm_tmysql4#1]
Hello,

I can't login to my Facepunch account (for whatever reason) so I thought the next best thing was to post something here.

The host I am running my server with is running CentOS 6 and the tmysql4 module appears not to work on that system. Doesn't work on a local test I did either but works fine on Ubuntu 14.04.

2924: /home/gmodserver/serverfiles/garrysmod/lua/bin/gmsv_tmysql4_linux.dll: error: symbol lookup error: undefined symbol: clock_gettime (fatal)

Its handing out that error on the test that I did on my local machine.

I did some of the stuff that was suggested in this thread https://facepunch.com/showthread.php?t=1490775 so.

So I did these two things.

This,

[gmodserver@vultr bin]$ ldd gmsv_tmysql4_linux.dll
        linux-gate.so.1 =>  (0x002b4000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x0018b000)
        libm.so.6 => /lib/libm.so.6 (0x00941000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x0012e000)
        libc.so.6 => /lib/libc.so.6 (0x002ca000)
        /lib/ld-linux.so.2 (0x0016b000)

And this,

[gmodserver@vultr bin]$ strings libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_FORCE_NEW
GLIBCXX_DEBUG_MESSAGE_LENGTH

I don't really know if there is much you can do, but I'm kind of stuck with the host I am with and because its shared hosting I can't really do much to modify the system (As much as I hate shared hosting I can't switch off it right now).

I'll post this on the facepunch thread if I can ever get into my account.

Sorry if some of the grammar or spelling is sloppy in this, just I'm running on no sleep and its already 6am here... So I'm tired as fuck.

Thanks in advanced,
Main Fighter.

**Comment by bkacjios** [comment]
I saw this happen on another older machine. I could probably compile a version that disables the timers which should fix the issue for you. I'll try and do that sometime tomorrow.

**Comment by MainFighter** [comment]
Okay, thanks...
I didn't wanna be stuck using mysqloo.

**Comment by bkacjios** [comment]
Alright.

https://dl.dropboxusercontent.com/u/38214687/gmsv_tmysql4_linux.dll

I think I fixed the issue. I had to link librt as a dependency. For some reason clock_gettime is defined in that on some glibc versions instead.

**Comment by MainFighter** [comment]
That module appears to be working, thank you.

**Comment by bkacjios** [comment]
Awesome. Thanks for letting me know.
