### ISSUE TITLE
I'm having a weird issue going on rn involving this module

### ISSUE THREAD

**Issue by VaasKahnGrim** [blackawps/gm_tmysql4#6]
So right now I have my gamemode using this module for handling MySQL stuff. However I also have an addon created by a company named WiltOS which uses gmsv_mysqloo. I'm not yet sure which of the 2 modules is causing this to happen but this is what I'm noticing. in the console of srcds it would seem that everything is fine, however I attached to process in visual studio 2019 to look into something else and I noticed this being spit out alot into the output section of the debugger: `Exception thrown at 0753A3DB2 in srcds.exe: Microsoft C++ exception: MySQLException at memory location 0x287BF884`

Any idea what exactly is going on here?

**Comment by bkacjios** [comment]
I haven't worked on this module in years. I'm pretty sure there's an active fork that gets updates. https://github.com/SuperiorServers/gm_tmysql4
